/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output.Spareparts;

import Database.DB;
import Output.FormLogin;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Timestamp;

/**
 *
 * @author milea
 */
public class FormSpareparts extends javax.swing.JFrame {

    DB db;
    int userId;
    ListSpareparts listSparepart;

    /**
     * Creates new form ListCustomer
     *
     * @param listSpareparts
     * @param userId
     */
    public FormSpareparts(ListSpareparts listSpareparts, int userId) {
        this.db = new DB(new String[]{"spareparts", "sparepart_id"});
        this.listSparepart = listSpareparts;
        this.userId = userId;
        initComponents();
    }

    public FormSpareparts() {
        new FormLogin().setVisible(true);
        this.setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputNamaSparepart = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        inputQtySparepart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputHargaJualSparepart = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDeskripsiSparepart = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sparepart");

        jLabel2.setText("Nama");

        jLabel3.setText("Deskripsi");

        jLabel4.setText("Qty");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        inputQtySparepart.setText("0");

        jLabel5.setText("Harga Jual");

        inputHargaJualSparepart.setText("0");

        inputDeskripsiSparepart.setColumns(20);
        inputDeskripsiSparepart.setRows(5);
        jScrollPane1.setViewportView(inputDeskripsiSparepart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputHargaJualSparepart)
                    .addComponent(inputNamaSparepart)
                    .addComponent(inputQtySparepart)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTambah))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNamaSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQtySparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHargaJualSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String namaSparepart = inputNamaSparepart.getText().trim();
        String detailSparepart = inputDeskripsiSparepart.getText().trim();
        int qtySparepart = Integer.parseInt(inputQtySparepart.getText().trim());
        int hargaSparepart = Integer.parseInt(inputHargaJualSparepart.getText().trim());
        if (namaSparepart.isEmpty() || detailSparepart.isEmpty()) {
            this.peringatan("Data tidak boleh kosong!");
        } else {
            try {
                String query = "INSERT INTO pareparts(sparepart_nama,sparepart_deskripsi,sparepart_qty,sparepart_harga,sparepart_created_at,sparepart_updated_at) VALUES(?,?,?,?,?,?);";
                Timestamp currentTimeStamp = new Timestamp(System.currentTimeMillis());
                PreparedStatement preparedStatement = db.getPrepStatement(query);
                preparedStatement.setString(1, namaSparepart);
                preparedStatement.setString(2, detailSparepart);
                preparedStatement.setInt(3, qtySparepart);
                preparedStatement.setInt(4, hargaSparepart);
                preparedStatement.setTimestamp(5, currentTimeStamp);
                preparedStatement.setTimestamp(6, currentTimeStamp);
                if (preparedStatement.executeUpdate() <= 0) {
                    this.peringatan("Gagal menyimpan spareparts!");
                } else {
                    this.peringatan("Berhasil menyimpan spareparts!");
                    this.dispose();
                    ((ListSpareparts) listSparepart).loadTabel();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSpareparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSpareparts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextArea inputDeskripsiSparepart;
    private javax.swing.JTextField inputHargaJualSparepart;
    private javax.swing.JTextField inputNamaSparepart;
    private javax.swing.JTextField inputQtySparepart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
