/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output.Mobil;

import Database.Cars;
import Output.FormLogin;
import Output.MainFrame;
import Output.Project.FormProject;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.persistence.TypedQuery;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milea
 */
public class CariMobil extends MainFrame {

    ArrayList<Cars> listMobil = new ArrayList<>();
    Cars selectedMobil;
    int userId;
    Object obj;

    /**
     * Creates new form ListCustomer
     *
     * @param obj
     * @param userId
     */
    public CariMobil(Object obj, int userId) {
        this.obj = obj;
        this.userId = userId;
        initComponents();
        this.loadTabel();
    }

    public CariMobil() {
        new FormLogin().setVisible(true);
        this.setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMobil = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAddMobil = new javax.swing.JButton();
        filterBy = new javax.swing.JComboBox<>();
        btnPilihMobil = new javax.swing.JButton();
        btnUpdateMobil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cari Mobil");

        tableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Pabrikan", "Tipe", "Besar CC", "Tahun"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMobil);

        inputSearch.setText("Search");
        inputSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputSearchKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 15)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/base-50x50.png"))); // NOI18N
        jLabel1.setText("Tambah Project");

        btnAddMobil.setBackground(new java.awt.Color(192, 242, 100));
        btnAddMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/plus-30x30.png"))); // NOI18N
        btnAddMobil.setText("Tambah");
        btnAddMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMobilActionPerformed(evt);
            }
        });

        filterBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Pabrikan", "Tipe", "CC", "Tahun" }));

        btnPilihMobil.setBackground(new java.awt.Color(192, 242, 100));
        btnPilihMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/choose-30x30.png"))); // NOI18N
        btnPilihMobil.setText("Pilih Mobil");
        btnPilihMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMobilActionPerformed(evt);
            }
        });

        btnUpdateMobil.setBackground(new java.awt.Color(192, 242, 100));
        btnUpdateMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Img/pencil-30x30.png"))); // NOI18N
        btnUpdateMobil.setText("Ubah Data");
        btnUpdateMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMobilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateMobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPilihMobil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAddMobil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filterBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMobil)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilihMobil)
                    .addComponent(btnUpdateMobil))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.loadTabel();
        }
    }//GEN-LAST:event_inputSearchKeyTyped

    private void tableMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMobilMouseClicked
        // TODO add your handling code here:
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();
        int indexId = Integer.parseInt(target.getModel().getValueAt(row, 0).toString());
        System.out.println(indexId);
        this.selectedMobil = listMobil.get(indexId - 1);
    }//GEN-LAST:event_tableMobilMouseClicked

    private void btnAddMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMobilActionPerformed
        // TODO add your handling code here:
        new FormMobil(this, userId).setVisible(true);
    }//GEN-LAST:event_btnAddMobilActionPerformed

    private void btnPilihMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMobilActionPerformed
        // TODO add your handling code here:
        if(this.obj instanceof FormProject){
            ((FormProject) obj).setCarName(selectedMobil);
            this.dispose();
        }else{
            this.peringatan("ini bukan instance dari form project");
        }
    }//GEN-LAST:event_btnPilihMobilActionPerformed

    private void btnUpdateMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMobilActionPerformed
        // TODO add your handling code here:
        new FormMobilEdit(this, selectedMobil.getMobilId()).setVisible(true);
    }//GEN-LAST:event_btnUpdateMobilActionPerformed

    public void loadTabel() {
        String search = inputSearch.getText();
        if (search.equalsIgnoreCase("string")) {
            search = "";
        }
        int queryIndex = filterBy.getSelectedIndex();
        DefaultTableModel model = (DefaultTableModel) tableMobil.getModel();
        model.setRowCount(0);
        try {
            String namedQuery = "Cars.findAll";
//            Nama, Pabrikan, Tipe, CC, Tahun
            if (!search.equals("")) {
                namedQuery = "Cars.findByLikeMobilNama";
                if (queryIndex == 1) {
                    namedQuery = "Cars.findByLikeMobilPabrikan";
                } else if (queryIndex == 2) {
                    namedQuery = "Cars.findByLikeMobilTipe";
                } else if (queryIndex == 3) {
                    namedQuery = "Cars.findByMobilTahun";
                } else if (queryIndex == 4) {
                    namedQuery = "Cars.findByLikeMobilTahun";
                }
            }

            TypedQuery<Cars> queryByCars = entityManager.createNamedQuery(namedQuery, Cars.class);
            if (!search.equals("")) {
                if (queryIndex == 3) {
                    queryByCars.setParameter("parameter", search);
                } else {
                    queryByCars.setParameter("parameter", "%" + search + "%");
                }
            }

            int i = 1;
            listMobil.clear();
            for (Cars mobil : queryByCars.getResultList()) {
                Object[] baris = new Object[6];
                baris[0] = i++;
                listMobil.add(mobil);
                baris[1] = mobil.getMobilNama();
                baris[2] = mobil.getMobilPabrikan();
                baris[3] = mobil.getMobilTipe();
                baris[4] = mobil.getMobilKapasitasMesin();
                baris[5] = mobil.getMobilTahun();
                model.addRow(baris);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CariMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMobil;
    private javax.swing.JButton btnPilihMobil;
    private javax.swing.JButton btnUpdateMobil;
    private javax.swing.JComboBox<String> filterBy;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMobil;
    // End of variables declaration//GEN-END:variables
}
